# Changes here will be overwritten by Copier
_commit: v1.2.1
_src_path: gh:lincc-frameworks/python-project-template
author_email: lincc-frameworks-team@lists.lsst.org
author_name: LINCC Frameworks
create_example_module: false
module_name: lsdb
preferred_linter: pylint
project_name: lsdb
use_isort: true
