# Changes here will be overwritten by Copier
_commit: v2.2.0
_src_path: gh:lincc-frameworks/python-project-template
author_email: lincc-frameworks-team@lists.lsst.org
author_name: LINCC Frameworks
create_example_module: false
custom_install: custom
enforce_style:
- pylint
- black
- isort
failure_notification:
- slack
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: basic
package_name: lsdb
project_description: Spatial analysis for extremely large astronomical catalogs using
    dask
project_license: BSD
project_name: lsdb
project_organization: astronomy-commons
python_versions:
- '3.11'
- '3.12'
- '3.13'
- '3.14'
test_lowest_version: direct
