# This workflow will run benchmarks with airspeed velocity (asv) for pull requests.
# It will compare the performance of the main branch with the performance of the merge
# with the new changes and publish a comment with this assessment.  

name: Run ASV benchmarks for PR

on:
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.10"
  WORKING_DIR: ${{ github.workspace }}/benchmarks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  setup-python:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Python ${{ env.PYTHON_VERSION }}
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: python-${{ env.PYTHON_VERSION }}

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.PYTHON_VERSION }}"

  asv-pr:
    runs-on: ubuntu-latest
    needs: setup-python

    permissions:
      actions: read
      pull-requests: write

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: Checkout PR branch of the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Python ${{ env.PYTHON_VERSION }}
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: python-${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install asv==0.5.1 virtualenv tabulate lf-asv-formatter

      - name: Get current job logs URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Create ASV machine config file
        run: asv machine --machine gh-runner --yes

      - name: Run comparison of PR against main branch
        run: |
          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream
          asv continuous upstream/main HEAD || true
          asv compare upstream/main HEAD --sort ratio | tee output
          python -m lf_asv_formatter
          printf "\n\nClick [here]($STEP_URL) to view all benchmarks." >> output
        env:
          STEP_URL: "${{ steps.jobs.outputs.html_url }}#step:8:1"

      - name: Publish comment to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');

            const workingDir = process.env.WORKING_DIR;
            try {
              process.chdir(workingDir);
              const comment = fs.readFileSync('output', 'utf-8');
              const { data } = await github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: comment,
              });
              console.log('Comment published:', data.html_url);
            } catch (err) {
              console.error(err);
            }