# This workflow will run daily at 06:45.
# It will run benchmarks with airspeed velocity (asv)
# and compare performance with the previous nightly build.
name: Run benchmarks nightly job

on:
  schedule:
    - cron: 45 6 * * *
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"
  ASV_VERSION: "0.6.4"
  WORKING_DIR: ${{github.workspace}}/benchmarks
  CURRENT_HASH: ${{github.sha}}
  NIGHTLY_HASH_FILE: nightly-hash

jobs:
  asv-nightly:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORKING_DIR}}
    steps:
    - name: Set up Python ${{env.PYTHON_VERSION}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{env.PYTHON_VERSION}}
    - name: Checkout main branch of the repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Install dependencies
      run: pip install asv[virtualenv]==$ASV_VERSION
    - name: Create ASV machine config file
      run: asv machine --machine gh-runner --yes
    - name: Get nightly dates under comparison
      id: nightly-dates
      run: |
        echo "yesterday=$(date -d yesterday +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - name: Use last nightly commit hash from cache
      uses: actions/cache@v4
      with:
        path: ${{env.WORKING_DIR}}/${{env.NIGHTLY_HASH_FILE}}
        key: commit-hash-${{steps.nightly-dates.outputs.yesterday}}
    - name: Compare main against last nightly build
      id: asv_compare
      run: |
        if [ -s $NIGHTLY_HASH_FILE ]; then
          PREV_HASH=$(cat $NIGHTLY_HASH_FILE)
          asv continuous $PREV_HASH $CURRENT_HASH --factor 1.5 --verbose
        fi
      continue-on-error: true
    - name: Update commit hash
      if: always()
      run: echo $CURRENT_HASH > $NIGHTLY_HASH_FILE
    - name: Upload current commit hash to cache
      if: always()
      uses: actions/cache@v4
      with:
        path: ${{env.WORKING_DIR}}/${{env.NIGHTLY_HASH_FILE}}
        key: commit-hash-${{steps.nightly-dates.outputs.today}}
    - name: Fail workflow
      if: steps.asv_compare.outcome == 'failure'
      run: exit 1
    - name: Send status to Slack app
      if: ${{ failure() && github.event_name != 'workflow_dispatch' }}
      id: slack
      uses: slackapi/slack-github-action@v2
      with:
        # For posting a rich message using Block Kit
        webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
        webhook-type: webhook-trigger
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "${{ github.repository }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action benchmark result: *${{ job.status }}* :${{ job.status }}:"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
              }
            ]
          }
